services:
  - type: web
    name: droproom
    env: node
    buildCommand: bun install && bun build && bun run db:push
    startCommand: bun start
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: dxtujnsmb
      - key: CLOUDINARY_API_KEY
        value: "785721964931176"
      - key: CLOUDINARY_API_SECRET
        value: dgVPHq6y6xIW9v1p_P0ae9hjsBg
      - key: DATABASE_URL
        fromDatabase:
          name: droproom
          property: connectionString
